name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  beefore:
    name: Pre-test checks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        task:
        - 'flake8'
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -U setuptools
        pip install tox
    - name: Run pre-test check
      run: |
        tox -e ${{ matrix.task }}

  test:
    name: Test App
    needs: beefore
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -U setuptools
        pip install tox
    - name: Test
      env:
        AWS_ACCESS_KEY_ID: AKIAX7VXJHRLKP7L6NHV
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        tox -e py
